### ISSUE TITLE
Can't create table (Error #150 "Foreign key constraint is incorrectly formed")

### ISSUE THREAD

**Issue by Sama34** [kawaiiforums/mybb-mint-shop#1]
Upon installation I got the following error:

![image](https://user-images.githubusercontent.com/1786584/74586358-9c5bab80-4f9b-11ea-811a-b0fdae1fd30b.png)

Issue seems to be line #65 at ItemTransactions.php, the table name was missing the prefix "mint_"

**Comment by dvz** [comment]
Resolved via https://github.com/kawaiiforums/mybb-mint/commit/ab93afd51e658a9a6d30634e31210396ad0aa1a5
